[package]
name = "e710_uhf"
version = "0.2.0"
edition = "2024"
exclude = ["docs/"]
description = "A Rust library for interacting with E710 UHF RFID modules"
license = "MIT"

[dependencies]
log = "0.4.29"

# Dipendenze opzionali per async
async-trait = { version = "0.1.89", optional = true }
tokio = { version = "1", features = ["io-util", "time"], optional = true }

[features]
default = []           # la feature async non è attiva di default
async = ["tokio", "async-trait"]


[dev-dependencies]
paste = "1.0.15"
env_logger = "0.11"
chrono = "0.4"
serialport = "4.8.1"
tokio-serial = "5.4.5"
## Tokio serve per compilare/girare gli esempi async che usano #[tokio::main]
## Qui abilitiamo le feature necessarie al runtime e alle macro, senza
## richiedere l'attivazione della feature opzionale della libreria.
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-util"] }



[workspace.metadata.cross.target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get --assume-yes install libudev-dev:$CROSS_DEB_ARCH"
]
